- hosts: nginx
  become: true
  roles:
    - nginx

- hosts: nexus
  become: true
  roles:
    - nexus

- hosts: gitlab
  become: true
  roles:
    - gitlab


- hosts: gitlab
  become: true
  roles:
    - docker
    - gitlab-runner
