- name: nexus unit reload
  systemd:
    daemon_reload: yes
    name: nexus.service

- name: nexus stop
  systemd:
    name: nexus.service
    state: stopped

- name: nexus start
  systemd:
    name: nexus.service
    state: started

- name: nexus restart
  systemd:
    name: nexus.service
    state: restarted

- name: nexus wait port
  wait_for:
    port: 8081
    timeout: 600
